---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:${JFIN_VERS}
    container_name: jellyfin
    hostname: swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JELLYFIN_PublishedServerUrl=${JFIN_IP} #optional
    volumes:
      - ./jfin/config:/config
      - /media/plexmedia/Series:/data/tvshows
      - /media/plexmedia/Anime:/data/anime
      - /media/plexmedia/Movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag:${SWAG_VERS}
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=${SWAG_URL}
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - DUCKDNSTOKEN= #optional
      # - EMAIL= #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
      # - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
